//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceMML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movies
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public byte[] Poster { get; set; }
        public Nullable<System.DateTime> YourSeanceDate { get; set; }
        public int Score { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string UpdateType { get; set; }
    }
}
